# Generated by Django 5.1 on 2024-08-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='username',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default='test123@gmail.com', max_length=100),
        ),
        migrations.DeleteModel(
            name='MessageLog',
        ),
    ]
