# Generated by Django 5.1 on 2024-08-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0003_remove_login_username_login_email_delete_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
