# Generated by Django 5.1 on 2024-08-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0004_login_phone'),
        ('chatAPI', '0005_alter_contact_phone'),
    ]

    operations = [
    ]
