# Generated by Django 5.1 on 2024-08-15 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0009_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
