# Generated by Django 5.1 on 2024-08-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0011_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
