# Generated by Django 5.1 on 2024-08-25 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatAPI', '0013_chathistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
